---
resource_types:

- name: cf-cli-resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest

resources:

- name: sensors-demo
  type: git
  source:
    uri: https://github.com/cpage-pivotal/spring-boot-demo
    branch: master

- name: pcf-env
  type: cf-cli-resource
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASSWORD}}
    skip_cert_check: true
    org: {{CF_ORG}}
    space: {{CF_SPACE}}

jobs:

- name: build-deploy
  plan:
  - get: sensors-demo
    trigger: true
  - task: build-jar
    file: sensors-demo/ci/build-sensor.yml
  - put: cf-push
    resource: pcf-env
    params:
      command: push
      app_name: sensors
      manifest: sensors-demo/ci/manifest.yml

